name: CD docker

on:
  workflow_run:
    workflows: ['CI docker']
    types:
      - completed

jobs:
  starts:
      runs-on: [self-hosted, be-fiverr-system]

      steps:
        # Tạo folder _work trên máy ảo và lấy file docker-compose.yml
        - name: Checkout mã nguồn
          uses: actions/checkout@v4 

        - name: Dọn dẹp container hệ thống trên máy ảo trên dockerhub
          run: |
            sudo docker container stop con-be-fiverr-system || true
            sudo docker container rm con-be-fiverr-system || true

        - name: Kéo bản mới và deploy container
          run: |
            docker compose pull
            docker compose up -d