name: CD docker

on:
  workflow_run:
    workflows: ['CI docker']
    types:
      - completed

jobs:
  starts:
    runs-on: [self-hosted, be-fiverr-system]

    steps:
      - name: Dừng container cũ
        run: sudo docker container stop con-be-fiverr-system

      - name: Xoá container cũ
        run: sudo docker container remove con-be-fiverr-system

      - name: Xoá image cũ
        run: sudo docker image remove cuongvan/img-be-fiverr-system:latest

      - name: Kéo và chạy lại image trên docker hub
        run: docker compose up -d